# Generated by Django 4.2.19 on 2026-01-22 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Plan to Watch', 'Plan to Watch'), ('Watching', 'Watching'), ('Completed', 'Completed'), ('On Hold', 'On Hold'), ('Dropped', 'Dropped')], default='Plan to Watch', max_length=50)),
                ('rate', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
                ('genres', models.ManyToManyField(blank=True, to='media.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media.media')),
                ('duration', models.PositiveIntegerField(blank=True, help_text='Duration in minutes', null=True)),
                ('release_year', models.PositiveIntegerField(blank=True, null=True)),
            ],
            bases=('media.media',),
        ),
        migrations.CreateModel(
            name='TvShow',
            fields=[
                ('media_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='media.media')),
                ('episodes', models.PositiveIntegerField(blank=True, null=True)),
                ('seasons', models.PositiveIntegerField(blank=True, null=True)),
            ],
            bases=('media.media',),
        ),
    ]
