# Generated by Django 4.2.19 on 2026-01-21 22:18
from django.db import migrations


# Initial genres seed
def create_genres(apps, schema_editor):
    Genre = apps.get_model('media', 'Genre')

    genres = [
        "Action",
        "Adventure",
        "Animation",
        "Anime",
        "Biography",
        "Comedy",
        "Crime",
        "Documentary",
        "Drama",
        "Fantasy",
        "Family",
        "Horror",
        "Mystery",
        "Reality",
        "Romance",
        "Sci-Fi",
        "Thriller",
        "War",
        "Western",
    ]

    for name in genres:
        Genre.objects.get_or_create(name=name)


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_genres),
    ]
